// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin_service.proto

package grpc_admin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqStart_Mode int32

const (
	ReqStart_DEFAULT ReqStart_Mode = 0
	ReqStart_MONITOR ReqStart_Mode = 1
)

var ReqStart_Mode_name = map[int32]string{
	0: "DEFAULT",
	1: "MONITOR",
}

var ReqStart_Mode_value = map[string]int32{
	"DEFAULT": 0,
	"MONITOR": 1,
}

func (x ReqStart_Mode) String() string {
	return proto.EnumName(ReqStart_Mode_name, int32(x))
}

func (ReqStart_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{4, 0}
}

//TODO : 각 메시지별  내부 스펙들은 변경 될 수 있음.
type ReqSetupKey struct {
	SetupPort            string   `protobuf:"bytes,1,opt,name=setup_port,json=setupPort,proto3" json:"setup_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSetupKey) Reset()         { *m = ReqSetupKey{} }
func (m *ReqSetupKey) String() string { return proto.CompactTextString(m) }
func (*ReqSetupKey) ProtoMessage()    {}
func (*ReqSetupKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{0}
}

func (m *ReqSetupKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSetupKey.Unmarshal(m, b)
}
func (m *ReqSetupKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSetupKey.Marshal(b, m, deterministic)
}
func (m *ReqSetupKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSetupKey.Merge(m, src)
}
func (m *ReqSetupKey) XXX_Size() int {
	return xxx_messageInfo_ReqSetupKey.Size(m)
}
func (m *ReqSetupKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSetupKey.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSetupKey proto.InternalMessageInfo

func (m *ReqSetupKey) GetSetupPort() string {
	if m != nil {
		return m.SetupPort
	}
	return ""
}

type ResSetupKey struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResSetupKey) Reset()         { *m = ResSetupKey{} }
func (m *ResSetupKey) String() string { return proto.CompactTextString(m) }
func (*ResSetupKey) ProtoMessage()    {}
func (*ResSetupKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{1}
}

func (m *ResSetupKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResSetupKey.Unmarshal(m, b)
}
func (m *ResSetupKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResSetupKey.Marshal(b, m, deterministic)
}
func (m *ResSetupKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResSetupKey.Merge(m, src)
}
func (m *ResSetupKey) XXX_Size() int {
	return xxx_messageInfo_ResSetupKey.Size(m)
}
func (m *ResSetupKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ResSetupKey.DiscardUnknown(m)
}

var xxx_messageInfo_ResSetupKey proto.InternalMessageInfo

func (m *ResSetupKey) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResSetupKey) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ReqLogin struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{2}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResLogin struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResLogin) Reset()         { *m = ResLogin{} }
func (m *ResLogin) String() string { return proto.CompactTextString(m) }
func (*ResLogin) ProtoMessage()    {}
func (*ResLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{3}
}

func (m *ResLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResLogin.Unmarshal(m, b)
}
func (m *ResLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResLogin.Marshal(b, m, deterministic)
}
func (m *ResLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResLogin.Merge(m, src)
}
func (m *ResLogin) XXX_Size() int {
	return xxx_messageInfo_ResLogin.Size(m)
}
func (m *ResLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ResLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ResLogin proto.InternalMessageInfo

func (m *ResLogin) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResLogin) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ReqStart struct {
	Mode                 ReqStart_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=grpc_admin.ReqStart_Mode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqStart) Reset()         { *m = ReqStart{} }
func (m *ReqStart) String() string { return proto.CompactTextString(m) }
func (*ReqStart) ProtoMessage()    {}
func (*ReqStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{4}
}

func (m *ReqStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStart.Unmarshal(m, b)
}
func (m *ReqStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStart.Marshal(b, m, deterministic)
}
func (m *ReqStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStart.Merge(m, src)
}
func (m *ReqStart) XXX_Size() int {
	return xxx_messageInfo_ReqStart.Size(m)
}
func (m *ReqStart) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStart.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStart proto.InternalMessageInfo

func (m *ReqStart) GetMode() ReqStart_Mode {
	if m != nil {
		return m.Mode
	}
	return ReqStart_DEFAULT
}

type ResStart struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResStart) Reset()         { *m = ResStart{} }
func (m *ResStart) String() string { return proto.CompactTextString(m) }
func (*ResStart) ProtoMessage()    {}
func (*ResStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{5}
}

func (m *ResStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResStart.Unmarshal(m, b)
}
func (m *ResStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResStart.Marshal(b, m, deterministic)
}
func (m *ResStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResStart.Merge(m, src)
}
func (m *ResStart) XXX_Size() int {
	return xxx_messageInfo_ResStart.Size(m)
}
func (m *ResStart) XXX_DiscardUnknown() {
	xxx_messageInfo_ResStart.DiscardUnknown(m)
}

var xxx_messageInfo_ResStart proto.InternalMessageInfo

func (m *ResStart) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResStart) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ReqStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqStatus) Reset()         { *m = ReqStatus{} }
func (m *ReqStatus) String() string { return proto.CompactTextString(m) }
func (*ReqStatus) ProtoMessage()    {}
func (*ReqStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{6}
}

func (m *ReqStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStatus.Unmarshal(m, b)
}
func (m *ReqStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStatus.Marshal(b, m, deterministic)
}
func (m *ReqStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStatus.Merge(m, src)
}
func (m *ReqStatus) XXX_Size() int {
	return xxx_messageInfo_ReqStatus.Size(m)
}
func (m *ReqStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStatus proto.InternalMessageInfo

type ResStatus struct {
	Alive                bool     `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResStatus) Reset()         { *m = ResStatus{} }
func (m *ResStatus) String() string { return proto.CompactTextString(m) }
func (*ResStatus) ProtoMessage()    {}
func (*ResStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{7}
}

func (m *ResStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResStatus.Unmarshal(m, b)
}
func (m *ResStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResStatus.Marshal(b, m, deterministic)
}
func (m *ResStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResStatus.Merge(m, src)
}
func (m *ResStatus) XXX_Size() int {
	return xxx_messageInfo_ResStatus.Size(m)
}
func (m *ResStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResStatus proto.InternalMessageInfo

func (m *ResStatus) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

type ReqLoadWorld struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLoadWorld) Reset()         { *m = ReqLoadWorld{} }
func (m *ReqLoadWorld) String() string { return proto.CompactTextString(m) }
func (*ReqLoadWorld) ProtoMessage()    {}
func (*ReqLoadWorld) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{8}
}

func (m *ReqLoadWorld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLoadWorld.Unmarshal(m, b)
}
func (m *ReqLoadWorld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLoadWorld.Marshal(b, m, deterministic)
}
func (m *ReqLoadWorld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLoadWorld.Merge(m, src)
}
func (m *ReqLoadWorld) XXX_Size() int {
	return xxx_messageInfo_ReqLoadWorld.Size(m)
}
func (m *ReqLoadWorld) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLoadWorld.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLoadWorld proto.InternalMessageInfo

func (m *ReqLoadWorld) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ResLoadWorld struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResLoadWorld) Reset()         { *m = ResLoadWorld{} }
func (m *ResLoadWorld) String() string { return proto.CompactTextString(m) }
func (*ResLoadWorld) ProtoMessage()    {}
func (*ResLoadWorld) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{9}
}

func (m *ResLoadWorld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResLoadWorld.Unmarshal(m, b)
}
func (m *ResLoadWorld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResLoadWorld.Marshal(b, m, deterministic)
}
func (m *ResLoadWorld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResLoadWorld.Merge(m, src)
}
func (m *ResLoadWorld) XXX_Size() int {
	return xxx_messageInfo_ResLoadWorld.Size(m)
}
func (m *ResLoadWorld) XXX_DiscardUnknown() {
	xxx_messageInfo_ResLoadWorld.DiscardUnknown(m)
}

var xxx_messageInfo_ResLoadWorld proto.InternalMessageInfo

func (m *ResLoadWorld) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResLoadWorld) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ReqLoadChain struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLoadChain) Reset()         { *m = ReqLoadChain{} }
func (m *ReqLoadChain) String() string { return proto.CompactTextString(m) }
func (*ReqLoadChain) ProtoMessage()    {}
func (*ReqLoadChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{10}
}

func (m *ReqLoadChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLoadChain.Unmarshal(m, b)
}
func (m *ReqLoadChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLoadChain.Marshal(b, m, deterministic)
}
func (m *ReqLoadChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLoadChain.Merge(m, src)
}
func (m *ReqLoadChain) XXX_Size() int {
	return xxx_messageInfo_ReqLoadChain.Size(m)
}
func (m *ReqLoadChain) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLoadChain.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLoadChain proto.InternalMessageInfo

func (m *ReqLoadChain) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ResLoadChain struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResLoadChain) Reset()         { *m = ResLoadChain{} }
func (m *ResLoadChain) String() string { return proto.CompactTextString(m) }
func (*ResLoadChain) ProtoMessage()    {}
func (*ResLoadChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{11}
}

func (m *ResLoadChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResLoadChain.Unmarshal(m, b)
}
func (m *ResLoadChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResLoadChain.Marshal(b, m, deterministic)
}
func (m *ResLoadChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResLoadChain.Merge(m, src)
}
func (m *ResLoadChain) XXX_Size() int {
	return xxx_messageInfo_ResLoadChain.Size(m)
}
func (m *ResLoadChain) XXX_DiscardUnknown() {
	xxx_messageInfo_ResLoadChain.DiscardUnknown(m)
}

var xxx_messageInfo_ResLoadChain proto.InternalMessageInfo

func (m *ResLoadChain) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResLoadChain) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterEnum("grpc_admin.ReqStart_Mode", ReqStart_Mode_name, ReqStart_Mode_value)
	proto.RegisterType((*ReqSetupKey)(nil), "grpc_admin.ReqSetupKey")
	proto.RegisterType((*ResSetupKey)(nil), "grpc_admin.ResSetupKey")
	proto.RegisterType((*ReqLogin)(nil), "grpc_admin.ReqLogin")
	proto.RegisterType((*ResLogin)(nil), "grpc_admin.ResLogin")
	proto.RegisterType((*ReqStart)(nil), "grpc_admin.ReqStart")
	proto.RegisterType((*ResStart)(nil), "grpc_admin.ResStart")
	proto.RegisterType((*ReqStatus)(nil), "grpc_admin.ReqStatus")
	proto.RegisterType((*ResStatus)(nil), "grpc_admin.ResStatus")
	proto.RegisterType((*ReqLoadWorld)(nil), "grpc_admin.ReqLoadWorld")
	proto.RegisterType((*ResLoadWorld)(nil), "grpc_admin.ResLoadWorld")
	proto.RegisterType((*ReqLoadChain)(nil), "grpc_admin.ReqLoadChain")
	proto.RegisterType((*ResLoadChain)(nil), "grpc_admin.ResLoadChain")
}

func init() { proto.RegisterFile("admin_service.proto", fileDescriptor_f9bc00259dc38d22) }

var fileDescriptor_f9bc00259dc38d22 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x4d, 0xb5, 0xcf, 0x97, 0xdc, 0x88, 0x94, 0xb1, 0xc5, 0x18, 0x10, 0xea, 0x2c, 0xc4, 0x85,
	0x66, 0x51, 0x11, 0x04, 0x3f, 0xa0, 0x54, 0x05, 0xb1, 0xb5, 0x92, 0x56, 0x5c, 0xb8, 0x28, 0x31,
	0x19, 0x9b, 0x60, 0x9b, 0x49, 0x67, 0x26, 0x95, 0xfe, 0x02, 0xff, 0xb6, 0xcc, 0x47, 0x13, 0x49,
	0x0a, 0x8f, 0xec, 0xe6, 0xde, 0x73, 0xee, 0x39, 0x33, 0x37, 0x27, 0x70, 0x3f, 0x4a, 0xf6, 0x59,
	0xbe, 0xe1, 0x84, 0x1d, 0xb3, 0x98, 0x04, 0x05, 0xa3, 0x82, 0x22, 0xd8, 0xb2, 0x22, 0xde, 0x28,
	0x04, 0x3f, 0x03, 0x37, 0x24, 0x87, 0x15, 0x11, 0x65, 0xf1, 0x99, 0x9c, 0xd0, 0x23, 0x00, 0x2e,
	0xcf, 0x9b, 0x82, 0x32, 0xe1, 0xf5, 0xc6, 0xbd, 0xa7, 0x4e, 0xe8, 0xa8, 0xce, 0x57, 0xca, 0x04,
	0x7e, 0x2d, 0xd9, 0xbc, 0x62, 0x7b, 0x70, 0xcd, 0xcb, 0x38, 0x26, 0x9c, 0x2b, 0xaa, 0x1d, 0x9e,
	0x4b, 0x84, 0xa0, 0x9f, 0xe5, 0xbf, 0xa8, 0x77, 0x4b, 0x29, 0xa8, 0x33, 0x7e, 0x02, 0x76, 0x48,
	0x0e, 0x73, 0xba, 0xcd, 0x72, 0xe4, 0x83, 0x5d, 0x44, 0x9c, 0xff, 0xa1, 0x2c, 0x31, 0x2e, 0x55,
	0x8d, 0x5f, 0x49, 0x1e, 0xd7, 0xbc, 0x6e, 0x0e, 0x3f, 0x94, 0xc3, 0x4a, 0x44, 0x4c, 0xa0, 0xe7,
	0xd0, 0xdf, 0xd3, 0x84, 0xa8, 0xb1, 0x7b, 0x93, 0x87, 0x41, 0xfd, 0xe6, 0xe0, 0xcc, 0x09, 0x16,
	0x34, 0x21, 0xa1, 0xa2, 0xe1, 0x31, 0xf4, 0x65, 0x85, 0x5c, 0xb8, 0x7e, 0xff, 0xe1, 0xe3, 0xf4,
	0xdb, 0x7c, 0x3d, 0xb0, 0x64, 0xb1, 0x58, 0x7e, 0xf9, 0xb4, 0x5e, 0x86, 0x83, 0x9e, 0xb9, 0x96,
	0x16, 0xef, 0x76, 0x2d, 0x17, 0x1c, 0x6d, 0x29, 0x4a, 0x8e, 0x1f, 0xcb, 0x82, 0xeb, 0x02, 0x0d,
	0xe1, 0x2a, 0xda, 0x65, 0x47, 0x62, 0x54, 0x74, 0x81, 0x31, 0xdc, 0x55, 0x8b, 0x8a, 0x92, 0xef,
	0x94, 0xed, 0x12, 0xa9, 0x59, 0x44, 0x22, 0x35, 0x8b, 0x52, 0x67, 0xfc, 0x46, 0x72, 0x78, 0xcd,
	0xe9, 0x76, 0xa3, 0xda, 0x61, 0x96, 0x46, 0x59, 0x7e, 0x83, 0x83, 0xe6, 0x74, 0x72, 0x98, 0xfc,
	0xbd, 0x0d, 0x68, 0x4d, 0x44, 0x7a, 0xe2, 0x53, 0xb9, 0xf3, 0x95, 0x0e, 0x20, 0x7a, 0x07, 0x76,
	0x95, 0x9e, 0x07, 0xcd, 0x6f, 0x62, 0x00, 0xbf, 0x01, 0x54, 0x79, 0xc3, 0x16, 0x7a, 0x09, 0x57,
	0x3a, 0x18, 0xc3, 0xc6, 0xb0, 0xea, 0xfa, 0x8d, 0xae, 0x0e, 0x91, 0x1e, 0xd3, 0x1f, 0x6e, 0x78,
	0x29, 0x07, 0xad, 0x31, 0xd5, 0xc5, 0x16, 0x9a, 0x82, 0xf3, 0xdf, 0x86, 0x5b, 0x8e, 0x06, 0xf1,
	0xbd, 0x96, 0xab, 0x41, 0x6a, 0x09, 0xb3, 0xc2, 0x0b, 0x12, 0x0a, 0xb9, 0x28, 0xa1, 0x10, 0x6c,
	0xa1, 0xb7, 0xe0, 0xce, 0x52, 0x12, 0xff, 0x36, 0x99, 0x19, 0xb5, 0x9f, 0x20, 0x4a, 0xee, 0x8f,
	0xda, 0x6f, 0x90, 0x71, 0xb3, 0x7e, 0xde, 0x51, 0x3f, 0xfd, 0x8b, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xe0, 0x14, 0xfe, 0xd1, 0x0b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TethysAdminServiceClient is the client API for TethysAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TethysAdminServiceClient interface {
	SetupKey(ctx context.Context, in *ReqSetupKey, opts ...grpc.CallOption) (*ResSetupKey, error)
	Login(ctx context.Context, in *ReqLogin, opts ...grpc.CallOption) (*ResLogin, error)
	Start(ctx context.Context, in *ReqStart, opts ...grpc.CallOption) (*ResStart, error)
	LoadWorld(ctx context.Context, in *ReqLoadWorld, opts ...grpc.CallOption) (*ResLoadWorld, error)
	LoadChain(ctx context.Context, in *ReqLoadChain, opts ...grpc.CallOption) (*ResLoadChain, error)
	CheckStatus(ctx context.Context, in *ReqStatus, opts ...grpc.CallOption) (*ResStatus, error)
}

type tethysAdminServiceClient struct {
	cc *grpc.ClientConn
}

func NewTethysAdminServiceClient(cc *grpc.ClientConn) TethysAdminServiceClient {
	return &tethysAdminServiceClient{cc}
}

func (c *tethysAdminServiceClient) SetupKey(ctx context.Context, in *ReqSetupKey, opts ...grpc.CallOption) (*ResSetupKey, error) {
	out := new(ResSetupKey)
	err := c.cc.Invoke(ctx, "/grpc_admin.TethysAdminService/SetupKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tethysAdminServiceClient) Login(ctx context.Context, in *ReqLogin, opts ...grpc.CallOption) (*ResLogin, error) {
	out := new(ResLogin)
	err := c.cc.Invoke(ctx, "/grpc_admin.TethysAdminService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tethysAdminServiceClient) Start(ctx context.Context, in *ReqStart, opts ...grpc.CallOption) (*ResStart, error) {
	out := new(ResStart)
	err := c.cc.Invoke(ctx, "/grpc_admin.TethysAdminService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tethysAdminServiceClient) LoadWorld(ctx context.Context, in *ReqLoadWorld, opts ...grpc.CallOption) (*ResLoadWorld, error) {
	out := new(ResLoadWorld)
	err := c.cc.Invoke(ctx, "/grpc_admin.TethysAdminService/LoadWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tethysAdminServiceClient) LoadChain(ctx context.Context, in *ReqLoadChain, opts ...grpc.CallOption) (*ResLoadChain, error) {
	out := new(ResLoadChain)
	err := c.cc.Invoke(ctx, "/grpc_admin.TethysAdminService/LoadChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tethysAdminServiceClient) CheckStatus(ctx context.Context, in *ReqStatus, opts ...grpc.CallOption) (*ResStatus, error) {
	out := new(ResStatus)
	err := c.cc.Invoke(ctx, "/grpc_admin.TethysAdminService/CheckStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TethysAdminServiceServer is the server API for TethysAdminService service.
type TethysAdminServiceServer interface {
	SetupKey(context.Context, *ReqSetupKey) (*ResSetupKey, error)
	Login(context.Context, *ReqLogin) (*ResLogin, error)
	Start(context.Context, *ReqStart) (*ResStart, error)
	LoadWorld(context.Context, *ReqLoadWorld) (*ResLoadWorld, error)
	LoadChain(context.Context, *ReqLoadChain) (*ResLoadChain, error)
	CheckStatus(context.Context, *ReqStatus) (*ResStatus, error)
}

// UnimplementedTethysAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTethysAdminServiceServer struct {
}

func (*UnimplementedTethysAdminServiceServer) SetupKey(ctx context.Context, req *ReqSetupKey) (*ResSetupKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupKey not implemented")
}
func (*UnimplementedTethysAdminServiceServer) Login(ctx context.Context, req *ReqLogin) (*ResLogin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedTethysAdminServiceServer) Start(ctx context.Context, req *ReqStart) (*ResStart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedTethysAdminServiceServer) LoadWorld(ctx context.Context, req *ReqLoadWorld) (*ResLoadWorld, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadWorld not implemented")
}
func (*UnimplementedTethysAdminServiceServer) LoadChain(ctx context.Context, req *ReqLoadChain) (*ResLoadChain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadChain not implemented")
}
func (*UnimplementedTethysAdminServiceServer) CheckStatus(ctx context.Context, req *ReqStatus) (*ResStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStatus not implemented")
}

func RegisterTethysAdminServiceServer(s *grpc.Server, srv TethysAdminServiceServer) {
	s.RegisterService(&_TethysAdminService_serviceDesc, srv)
}

func _TethysAdminService_SetupKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSetupKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TethysAdminServiceServer).SetupKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_admin.TethysAdminService/SetupKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TethysAdminServiceServer).SetupKey(ctx, req.(*ReqSetupKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _TethysAdminService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TethysAdminServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_admin.TethysAdminService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TethysAdminServiceServer).Login(ctx, req.(*ReqLogin))
	}
	return interceptor(ctx, in, info, handler)
}

func _TethysAdminService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqStart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TethysAdminServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_admin.TethysAdminService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TethysAdminServiceServer).Start(ctx, req.(*ReqStart))
	}
	return interceptor(ctx, in, info, handler)
}

func _TethysAdminService_LoadWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqLoadWorld)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TethysAdminServiceServer).LoadWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_admin.TethysAdminService/LoadWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TethysAdminServiceServer).LoadWorld(ctx, req.(*ReqLoadWorld))
	}
	return interceptor(ctx, in, info, handler)
}

func _TethysAdminService_LoadChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqLoadChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TethysAdminServiceServer).LoadChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_admin.TethysAdminService/LoadChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TethysAdminServiceServer).LoadChain(ctx, req.(*ReqLoadChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _TethysAdminService_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TethysAdminServiceServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_admin.TethysAdminService/CheckStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TethysAdminServiceServer).CheckStatus(ctx, req.(*ReqStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _TethysAdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_admin.TethysAdminService",
	HandlerType: (*TethysAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetupKey",
			Handler:    _TethysAdminService_SetupKey_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _TethysAdminService_Login_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _TethysAdminService_Start_Handler,
		},
		{
			MethodName: "LoadWorld",
			Handler:    _TethysAdminService_LoadWorld_Handler,
		},
		{
			MethodName: "LoadChain",
			Handler:    _TethysAdminService_LoadChain_Handler,
		},
		{
			MethodName: "CheckStatus",
			Handler:    _TethysAdminService_CheckStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_service.proto",
}
