// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin_service.proto

package grpc_admin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//TODO : 각 메시지별  내부 스펙들은 변경 될 수 있음.
type ReqSetup struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSetup) Reset()         { *m = ReqSetup{} }
func (m *ReqSetup) String() string { return proto.CompactTextString(m) }
func (*ReqSetup) ProtoMessage()    {}
func (*ReqSetup) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{0}
}

func (m *ReqSetup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSetup.Unmarshal(m, b)
}
func (m *ReqSetup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSetup.Marshal(b, m, deterministic)
}
func (m *ReqSetup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSetup.Merge(m, src)
}
func (m *ReqSetup) XXX_Size() int {
	return xxx_messageInfo_ReqSetup.Size(m)
}
func (m *ReqSetup) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSetup.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSetup proto.InternalMessageInfo

func (m *ReqSetup) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResSetup struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResSetup) Reset()         { *m = ResSetup{} }
func (m *ResSetup) String() string { return proto.CompactTextString(m) }
func (*ResSetup) ProtoMessage()    {}
func (*ResSetup) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{1}
}

func (m *ResSetup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResSetup.Unmarshal(m, b)
}
func (m *ResSetup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResSetup.Marshal(b, m, deterministic)
}
func (m *ResSetup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResSetup.Merge(m, src)
}
func (m *ResSetup) XXX_Size() int {
	return xxx_messageInfo_ResSetup.Size(m)
}
func (m *ResSetup) XXX_DiscardUnknown() {
	xxx_messageInfo_ResSetup.DiscardUnknown(m)
}

var xxx_messageInfo_ResSetup proto.InternalMessageInfo

func (m *ResSetup) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ReqStart struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqStart) Reset()         { *m = ReqStart{} }
func (m *ReqStart) String() string { return proto.CompactTextString(m) }
func (*ReqStart) ProtoMessage()    {}
func (*ReqStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{2}
}

func (m *ReqStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStart.Unmarshal(m, b)
}
func (m *ReqStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStart.Marshal(b, m, deterministic)
}
func (m *ReqStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStart.Merge(m, src)
}
func (m *ReqStart) XXX_Size() int {
	return xxx_messageInfo_ReqStart.Size(m)
}
func (m *ReqStart) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStart.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStart proto.InternalMessageInfo

type ResStart struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResStart) Reset()         { *m = ResStart{} }
func (m *ResStart) String() string { return proto.CompactTextString(m) }
func (*ResStart) ProtoMessage()    {}
func (*ResStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{3}
}

func (m *ResStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResStart.Unmarshal(m, b)
}
func (m *ResStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResStart.Marshal(b, m, deterministic)
}
func (m *ResStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResStart.Merge(m, src)
}
func (m *ResStart) XXX_Size() int {
	return xxx_messageInfo_ResStart.Size(m)
}
func (m *ResStart) XXX_DiscardUnknown() {
	xxx_messageInfo_ResStart.DiscardUnknown(m)
}

var xxx_messageInfo_ResStart proto.InternalMessageInfo

func (m *ResStart) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ReqStop struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqStop) Reset()         { *m = ReqStop{} }
func (m *ReqStop) String() string { return proto.CompactTextString(m) }
func (*ReqStop) ProtoMessage()    {}
func (*ReqStop) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{4}
}

func (m *ReqStop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStop.Unmarshal(m, b)
}
func (m *ReqStop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStop.Marshal(b, m, deterministic)
}
func (m *ReqStop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStop.Merge(m, src)
}
func (m *ReqStop) XXX_Size() int {
	return xxx_messageInfo_ReqStop.Size(m)
}
func (m *ReqStop) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStop.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStop proto.InternalMessageInfo

type ResStop struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResStop) Reset()         { *m = ResStop{} }
func (m *ResStop) String() string { return proto.CompactTextString(m) }
func (*ResStop) ProtoMessage()    {}
func (*ResStop) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{5}
}

func (m *ResStop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResStop.Unmarshal(m, b)
}
func (m *ResStop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResStop.Marshal(b, m, deterministic)
}
func (m *ResStop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResStop.Merge(m, src)
}
func (m *ResStop) XXX_Size() int {
	return xxx_messageInfo_ResStop.Size(m)
}
func (m *ResStop) XXX_DiscardUnknown() {
	xxx_messageInfo_ResStop.DiscardUnknown(m)
}

var xxx_messageInfo_ResStop proto.InternalMessageInfo

func (m *ResStop) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ReqStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqStatus) Reset()         { *m = ReqStatus{} }
func (m *ReqStatus) String() string { return proto.CompactTextString(m) }
func (*ReqStatus) ProtoMessage()    {}
func (*ReqStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{6}
}

func (m *ReqStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStatus.Unmarshal(m, b)
}
func (m *ReqStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStatus.Marshal(b, m, deterministic)
}
func (m *ReqStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStatus.Merge(m, src)
}
func (m *ReqStatus) XXX_Size() int {
	return xxx_messageInfo_ReqStatus.Size(m)
}
func (m *ReqStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStatus proto.InternalMessageInfo

type ResStatus struct {
	Alive                bool     `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResStatus) Reset()         { *m = ResStatus{} }
func (m *ResStatus) String() string { return proto.CompactTextString(m) }
func (*ResStatus) ProtoMessage()    {}
func (*ResStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bc00259dc38d22, []int{7}
}

func (m *ResStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResStatus.Unmarshal(m, b)
}
func (m *ResStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResStatus.Marshal(b, m, deterministic)
}
func (m *ResStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResStatus.Merge(m, src)
}
func (m *ResStatus) XXX_Size() int {
	return xxx_messageInfo_ResStatus.Size(m)
}
func (m *ResStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResStatus proto.InternalMessageInfo

func (m *ResStatus) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func init() {
	proto.RegisterType((*ReqSetup)(nil), "grpc_admin.ReqSetup")
	proto.RegisterType((*ResSetup)(nil), "grpc_admin.ResSetup")
	proto.RegisterType((*ReqStart)(nil), "grpc_admin.ReqStart")
	proto.RegisterType((*ResStart)(nil), "grpc_admin.ResStart")
	proto.RegisterType((*ReqStop)(nil), "grpc_admin.ReqStop")
	proto.RegisterType((*ResStop)(nil), "grpc_admin.ResStop")
	proto.RegisterType((*ReqStatus)(nil), "grpc_admin.ReqStatus")
	proto.RegisterType((*ResStatus)(nil), "grpc_admin.ResStatus")
}

func init() { proto.RegisterFile("admin_service.proto", fileDescriptor_f9bc00259dc38d22) }

var fileDescriptor_f9bc00259dc38d22 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0x4c, 0x24, 0x4a, 0x93, 0xd7, 0x09, 0xa7, 0x95, 0x2a, 0x4f, 0x60, 0x10, 0x62, 0xca, 0x50,
	0xc4, 0xc8, 0x80, 0x18, 0xd8, 0xd3, 0x1f, 0x50, 0x05, 0xd7, 0x82, 0x88, 0x0f, 0x1b, 0x3f, 0xbb,
	0xfc, 0x71, 0x7e, 0x00, 0x7a, 0x7e, 0x0d, 0x48, 0x4d, 0x95, 0xed, 0xdd, 0xe5, 0x2e, 0xa7, 0x3b,
	0x43, 0xd5, 0x6e, 0x3f, 0xba, 0xcf, 0x0d, 0x1a, 0xbf, 0xeb, 0xb4, 0xa9, 0x9d, 0xb7, 0xc1, 0x0a,
	0x78, 0xf1, 0x4e, 0x6f, 0xd2, 0x17, 0x75, 0x0d, 0x45, 0x63, 0xbe, 0xd6, 0x26, 0x44, 0x27, 0x24,
	0x14, 0xae, 0x45, 0xfc, 0xb6, 0x7e, 0xbb, 0xcc, 0xcf, 0xf3, 0x9b, 0xb2, 0xf9, 0xc3, 0xea, 0x8a,
	0x74, 0xc8, 0xba, 0x25, 0x4c, 0x31, 0x6a, 0x6d, 0x10, 0x93, 0xac, 0x68, 0x7a, 0xa8, 0x80, 0xff,
	0x16, 0x5a, 0x1f, 0x7a, 0x07, 0xdd, 0x23, 0x8e, 0x12, 0xa6, 0xc9, 0x61, 0x9d, 0xba, 0xa4, 0x13,
	0xe9, 0x1c, 0xd1, 0xcf, 0xa0, 0xe4, 0x84, 0x10, 0x51, 0x5d, 0x10, 0x40, 0x06, 0x62, 0x0e, 0x93,
	0xf6, 0xbd, 0xdb, 0x99, 0xbd, 0x83, 0xc1, 0xea, 0x27, 0x87, 0xb3, 0x27, 0x1f, 0x63, 0x78, 0xa0,
	0xba, 0x6b, 0xde, 0x41, 0xdc, 0xc1, 0x84, 0xab, 0xcc, 0xeb, 0xff, 0x2d, 0xea, 0x7e, 0x08, 0x79,
	0xc0, 0x72, 0x6d, 0x95, 0x25, 0x5b, 0xea, 0x33, 0x10, 0x10, 0x2b, 0x8f, 0xb2, 0x2a, 0x13, 0x2b,
	0x38, 0x49, 0xad, 0xaa, 0xc3, 0xb0, 0x60, 0x9d, 0xac, 0x06, 0x26, 0x4b, 0x51, 0xf7, 0x30, 0x7b,
	0x7c, 0x35, 0xfa, 0x6d, 0x5f, 0x6e, 0x31, 0xb0, 0x12, 0x2d, 0x17, 0xc3, 0x44, 0xda, 0x25, 0x7b,
	0x3e, 0x4d, 0x2f, 0x7d, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x99, 0xc1, 0x1c, 0x60, 0x00, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GruutAdminServiceClient is the client API for GruutAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GruutAdminServiceClient interface {
	Setup(ctx context.Context, in *ReqSetup, opts ...grpc.CallOption) (*ResSetup, error)
	Start(ctx context.Context, in *ResStart, opts ...grpc.CallOption) (*ResStart, error)
	Stop(ctx context.Context, in *ReqStop, opts ...grpc.CallOption) (*ResStop, error)
	CheckStatus(ctx context.Context, in *ReqStatus, opts ...grpc.CallOption) (*ResStatus, error)
}

type gruutAdminServiceClient struct {
	cc *grpc.ClientConn
}

func NewGruutAdminServiceClient(cc *grpc.ClientConn) GruutAdminServiceClient {
	return &gruutAdminServiceClient{cc}
}

func (c *gruutAdminServiceClient) Setup(ctx context.Context, in *ReqSetup, opts ...grpc.CallOption) (*ResSetup, error) {
	out := new(ResSetup)
	err := c.cc.Invoke(ctx, "/grpc_admin.GruutAdminService/Setup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gruutAdminServiceClient) Start(ctx context.Context, in *ResStart, opts ...grpc.CallOption) (*ResStart, error) {
	out := new(ResStart)
	err := c.cc.Invoke(ctx, "/grpc_admin.GruutAdminService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gruutAdminServiceClient) Stop(ctx context.Context, in *ReqStop, opts ...grpc.CallOption) (*ResStop, error) {
	out := new(ResStop)
	err := c.cc.Invoke(ctx, "/grpc_admin.GruutAdminService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gruutAdminServiceClient) CheckStatus(ctx context.Context, in *ReqStatus, opts ...grpc.CallOption) (*ResStatus, error) {
	out := new(ResStatus)
	err := c.cc.Invoke(ctx, "/grpc_admin.GruutAdminService/CheckStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GruutAdminServiceServer is the server API for GruutAdminService service.
type GruutAdminServiceServer interface {
	Setup(context.Context, *ReqSetup) (*ResSetup, error)
	Start(context.Context, *ResStart) (*ResStart, error)
	Stop(context.Context, *ReqStop) (*ResStop, error)
	CheckStatus(context.Context, *ReqStatus) (*ResStatus, error)
}

// UnimplementedGruutAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGruutAdminServiceServer struct {
}

func (*UnimplementedGruutAdminServiceServer) Setup(ctx context.Context, req *ReqSetup) (*ResSetup, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Setup not implemented")
}
func (*UnimplementedGruutAdminServiceServer) Start(ctx context.Context, req *ResStart) (*ResStart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedGruutAdminServiceServer) Stop(ctx context.Context, req *ReqStop) (*ResStop, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedGruutAdminServiceServer) CheckStatus(ctx context.Context, req *ReqStatus) (*ResStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStatus not implemented")
}

func RegisterGruutAdminServiceServer(s *grpc.Server, srv GruutAdminServiceServer) {
	s.RegisterService(&_GruutAdminService_serviceDesc, srv)
}

func _GruutAdminService_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSetup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GruutAdminServiceServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_admin.GruutAdminService/Setup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GruutAdminServiceServer).Setup(ctx, req.(*ReqSetup))
	}
	return interceptor(ctx, in, info, handler)
}

func _GruutAdminService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResStart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GruutAdminServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_admin.GruutAdminService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GruutAdminServiceServer).Start(ctx, req.(*ResStart))
	}
	return interceptor(ctx, in, info, handler)
}

func _GruutAdminService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqStop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GruutAdminServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_admin.GruutAdminService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GruutAdminServiceServer).Stop(ctx, req.(*ReqStop))
	}
	return interceptor(ctx, in, info, handler)
}

func _GruutAdminService_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GruutAdminServiceServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_admin.GruutAdminService/CheckStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GruutAdminServiceServer).CheckStatus(ctx, req.(*ReqStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _GruutAdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_admin.GruutAdminService",
	HandlerType: (*GruutAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Setup",
			Handler:    _GruutAdminService_Setup_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _GruutAdminService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _GruutAdminService_Stop_Handler,
		},
		{
			MethodName: "CheckStatus",
			Handler:    _GruutAdminService_CheckStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_service.proto",
}
