// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remote_control_service.proto

package grpc_remote_control

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestStatus) Reset()         { *m = RequestStatus{} }
func (m *RequestStatus) String() string { return proto.CompactTextString(m) }
func (*RequestStatus) ProtoMessage()    {}
func (*RequestStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3de1e02195d121b4, []int{0}
}

func (m *RequestStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestStatus.Unmarshal(m, b)
}
func (m *RequestStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestStatus.Marshal(b, m, deterministic)
}
func (m *RequestStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStatus.Merge(m, src)
}
func (m *RequestStatus) XXX_Size() int {
	return xxx_messageInfo_RequestStatus.Size(m)
}
func (m *RequestStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStatus proto.InternalMessageInfo

type ResponseStatus struct {
	Alive                bool     `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStatus) Reset()         { *m = ResponseStatus{} }
func (m *ResponseStatus) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus) ProtoMessage()    {}
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_3de1e02195d121b4, []int{1}
}

func (m *ResponseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStatus.Unmarshal(m, b)
}
func (m *ResponseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStatus.Marshal(b, m, deterministic)
}
func (m *ResponseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStatus.Merge(m, src)
}
func (m *ResponseStatus) XXX_Size() int {
	return xxx_messageInfo_ResponseStatus.Size(m)
}
func (m *ResponseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStatus proto.InternalMessageInfo

func (m *ResponseStatus) GetAlive() bool {
	if m != nil {
		return m.Alive
	}
	return false
}

func init() {
	proto.RegisterType((*RequestStatus)(nil), "grpc_remote_control.RequestStatus")
	proto.RegisterType((*ResponseStatus)(nil), "grpc_remote_control.ResponseStatus")
}

func init() { proto.RegisterFile("remote_control_service.proto", fileDescriptor_3de1e02195d121b4) }

var fileDescriptor_3de1e02195d121b4 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x4a, 0xcd, 0xcd,
	0x2f, 0x49, 0x8d, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0xcf, 0x89, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4e, 0x2f, 0x2a, 0x48, 0x8e, 0x47,
	0x55, 0xa2, 0xc4, 0xcf, 0xc5, 0x1b, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x12, 0x5c, 0x92, 0x58,
	0x52, 0x5a, 0xac, 0xa4, 0xc6, 0xc5, 0x17, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x0a, 0x11,
	0x11, 0x12, 0xe1, 0x62, 0x4d, 0xcc, 0xc9, 0x2c, 0x4b, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x08,
	0x82, 0x70, 0x8c, 0x0a, 0xb8, 0x44, 0x82, 0xc0, 0x46, 0x39, 0x43, 0x4c, 0x0a, 0x86, 0xd8, 0x25,
	0x14, 0xc1, 0xc5, 0xed, 0x9c, 0x91, 0x9a, 0x9c, 0x0d, 0xd5, 0xac, 0xa4, 0x87, 0xc5, 0x56, 0x3d,
	0x14, 0x2b, 0xa5, 0x94, 0x71, 0xa8, 0x41, 0x76, 0x85, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x1b, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x35, 0xa2, 0xa8, 0xe6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteControlServiceClient is the client API for RemoteControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteControlServiceClient interface {
	// Sends a greeting
	CheckStatus(ctx context.Context, in *RequestStatus, opts ...grpc.CallOption) (*ResponseStatus, error)
}

type remoteControlServiceClient struct {
	cc *grpc.ClientConn
}

func NewRemoteControlServiceClient(cc *grpc.ClientConn) RemoteControlServiceClient {
	return &remoteControlServiceClient{cc}
}

func (c *remoteControlServiceClient) CheckStatus(ctx context.Context, in *RequestStatus, opts ...grpc.CallOption) (*ResponseStatus, error) {
	out := new(ResponseStatus)
	err := c.cc.Invoke(ctx, "/grpc_remote_control.RemoteControlService/CheckStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteControlServiceServer is the server API for RemoteControlService service.
type RemoteControlServiceServer interface {
	// Sends a greeting
	CheckStatus(context.Context, *RequestStatus) (*ResponseStatus, error)
}

// UnimplementedRemoteControlServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRemoteControlServiceServer struct {
}

func (*UnimplementedRemoteControlServiceServer) CheckStatus(ctx context.Context, req *RequestStatus) (*ResponseStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStatus not implemented")
}

func RegisterRemoteControlServiceServer(s *grpc.Server, srv RemoteControlServiceServer) {
	s.RegisterService(&_RemoteControlService_serviceDesc, srv)
}

func _RemoteControlService_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteControlServiceServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_remote_control.RemoteControlService/CheckStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteControlServiceServer).CheckStatus(ctx, req.(*RequestStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteControlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_remote_control.RemoteControlService",
	HandlerType: (*RemoteControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckStatus",
			Handler:    _RemoteControlService_CheckStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "remote_control_service.proto",
}
