// Code generated by protoc-gen-go. DO NOT EDIT.
// source: merger_service.proto

package grpc_merger

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgStatus_Status int32

const (
	MsgStatus_SUCCESS    MsgStatus_Status = 0
	MsgStatus_INVALID    MsgStatus_Status = 1
	MsgStatus_INTERNAL   MsgStatus_Status = 2
	MsgStatus_DUPLICATED MsgStatus_Status = 3
)

var MsgStatus_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "INVALID",
	2: "INTERNAL",
	3: "DUPLICATED",
}

var MsgStatus_Status_value = map[string]int32{
	"SUCCESS":    0,
	"INVALID":    1,
	"INTERNAL":   2,
	"DUPLICATED": 3,
}

func (x MsgStatus_Status) String() string {
	return proto.EnumName(MsgStatus_Status_name, int32(x))
}

func (MsgStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d009ee599908743, []int{1, 0}
}

type RequestMsg struct {
	Broadcast            bool     `protobuf:"varint,1,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message              []byte   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMsg) Reset()         { *m = RequestMsg{} }
func (m *RequestMsg) String() string { return proto.CompactTextString(m) }
func (*RequestMsg) ProtoMessage()    {}
func (*RequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d009ee599908743, []int{0}
}

func (m *RequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMsg.Unmarshal(m, b)
}
func (m *RequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMsg.Marshal(b, m, deterministic)
}
func (m *RequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMsg.Merge(m, src)
}
func (m *RequestMsg) XXX_Size() int {
	return xxx_messageInfo_RequestMsg.Size(m)
}
func (m *RequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMsg proto.InternalMessageInfo

func (m *RequestMsg) GetBroadcast() bool {
	if m != nil {
		return m.Broadcast
	}
	return false
}

func (m *RequestMsg) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *RequestMsg) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type MsgStatus struct {
	Status               MsgStatus_Status `protobuf:"varint,1,opt,name=status,proto3,enum=grpc_merger.MsgStatus_Status" json:"status,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MsgStatus) Reset()         { *m = MsgStatus{} }
func (m *MsgStatus) String() string { return proto.CompactTextString(m) }
func (*MsgStatus) ProtoMessage()    {}
func (*MsgStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d009ee599908743, []int{1}
}

func (m *MsgStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgStatus.Unmarshal(m, b)
}
func (m *MsgStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgStatus.Marshal(b, m, deterministic)
}
func (m *MsgStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStatus.Merge(m, src)
}
func (m *MsgStatus) XXX_Size() int {
	return xxx_messageInfo_MsgStatus.Size(m)
}
func (m *MsgStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStatus proto.InternalMessageInfo

func (m *MsgStatus) GetStatus() MsgStatus_Status {
	if m != nil {
		return m.Status
	}
	return MsgStatus_SUCCESS
}

func (m *MsgStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("grpc_merger.MsgStatus_Status", MsgStatus_Status_name, MsgStatus_Status_value)
	proto.RegisterType((*RequestMsg)(nil), "grpc_merger.RequestMsg")
	proto.RegisterType((*MsgStatus)(nil), "grpc_merger.MsgStatus")
}

func init() { proto.RegisterFile("merger_service.proto", fileDescriptor_5d009ee599908743) }

var fileDescriptor_5d009ee599908743 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xcd, 0x6a, 0x83, 0x40,
	0x18, 0xcc, 0x26, 0x60, 0xe2, 0x97, 0x34, 0xc8, 0xb6, 0xb4, 0x52, 0x1a, 0x10, 0x4f, 0x9e, 0x3c,
	0xa4, 0xf4, 0x5e, 0xab, 0x1e, 0x04, 0x95, 0xb2, 0x9a, 0x42, 0x4f, 0x62, 0x74, 0xd9, 0xe6, 0x10,
	0x4c, 0xf7, 0xdb, 0x14, 0xfa, 0x32, 0x7d, 0xd6, 0x52, 0xb5, 0xf9, 0x81, 0x9c, 0x76, 0x67, 0x76,
	0x98, 0x99, 0x1d, 0xb8, 0xd9, 0x72, 0x29, 0xb8, 0x2c, 0x90, 0xcb, 0xaf, 0x4d, 0xc5, 0xdd, 0x9d,
	0x6c, 0x54, 0x43, 0xa7, 0x42, 0xee, 0xaa, 0xa2, 0x7b, 0xb2, 0x2b, 0x00, 0xc6, 0x3f, 0xf7, 0x1c,
	0x55, 0x82, 0x82, 0x3e, 0x80, 0xbe, 0x96, 0x4d, 0x59, 0x57, 0x25, 0x2a, 0x93, 0x58, 0xc4, 0x99,
	0xb0, 0x23, 0x41, 0x17, 0x00, 0x5b, 0x8e, 0x58, 0x0a, 0x5e, 0x6c, 0x6a, 0x73, 0x68, 0x11, 0x47,
	0x67, 0x7a, 0xcf, 0x44, 0x35, 0x35, 0x61, 0xdc, 0x03, 0x73, 0x64, 0x11, 0x67, 0xc6, 0xfe, 0xa1,
	0xfd, 0x43, 0x40, 0x4f, 0x50, 0x64, 0xaa, 0x54, 0x7b, 0xa4, 0x4f, 0xa0, 0x61, 0x7b, 0x6b, 0x13,
	0xe6, 0xcb, 0x85, 0x7b, 0x52, 0xc8, 0x3d, 0xe8, 0xdc, 0xee, 0x60, 0xbd, 0xf8, 0xd4, 0xbe, 0x8b,
	0x3e, 0xd8, 0x3f, 0x83, 0xd6, 0x5b, 0x4f, 0x61, 0x9c, 0xad, 0x7c, 0x3f, 0xcc, 0x32, 0x63, 0xf0,
	0x07, 0xa2, 0xf4, 0xcd, 0x8b, 0xa3, 0xc0, 0x20, 0x74, 0x06, 0x93, 0x28, 0xcd, 0x43, 0x96, 0x7a,
	0xb1, 0x31, 0xa4, 0x73, 0x80, 0x60, 0xf5, 0x1a, 0x47, 0xbe, 0x97, 0x87, 0x81, 0x31, 0x5a, 0xbe,
	0xc3, 0x75, 0xce, 0xd5, 0xc7, 0x37, 0x26, 0x6d, 0x89, 0xac, 0xdb, 0x8b, 0xbe, 0xc0, 0xd5, 0x39,
	0x71, 0x77, 0x56, 0xf5, 0x38, 0xdc, 0xfd, 0xed, 0xe5, 0x3f, 0xd8, 0x83, 0xb5, 0xd6, 0x8e, 0xfe,
	0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xb2, 0x8b, 0xbf, 0x8c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TethysMergerServiceClient is the client API for TethysMergerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TethysMergerServiceClient interface {
	MergerService(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*MsgStatus, error)
}

type tethysMergerServiceClient struct {
	cc *grpc.ClientConn
}

func NewTethysMergerServiceClient(cc *grpc.ClientConn) TethysMergerServiceClient {
	return &tethysMergerServiceClient{cc}
}

func (c *tethysMergerServiceClient) MergerService(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*MsgStatus, error) {
	out := new(MsgStatus)
	err := c.cc.Invoke(ctx, "/grpc_merger.TethysMergerService/MergerService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TethysMergerServiceServer is the server API for TethysMergerService service.
type TethysMergerServiceServer interface {
	MergerService(context.Context, *RequestMsg) (*MsgStatus, error)
}

// UnimplementedTethysMergerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTethysMergerServiceServer struct {
}

func (*UnimplementedTethysMergerServiceServer) MergerService(ctx context.Context, req *RequestMsg) (*MsgStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergerService not implemented")
}

func RegisterTethysMergerServiceServer(s *grpc.Server, srv TethysMergerServiceServer) {
	s.RegisterService(&_TethysMergerService_serviceDesc, srv)
}

func _TethysMergerService_MergerService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TethysMergerServiceServer).MergerService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_merger.TethysMergerService/MergerService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TethysMergerServiceServer).MergerService(ctx, req.(*RequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _TethysMergerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_merger.TethysMergerService",
	HandlerType: (*TethysMergerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MergerService",
			Handler:    _TethysMergerService_MergerService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merger_service.proto",
}
